version: "3"
services:
  db:
    image: mysql
    container_name: kowakunai_ec_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kowakunai_ec
      MYSQL_USER: kowakunai_fp
      MYSQL_PASSWORD: kowakunai_fp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
